language: python
python:
    - 3.6

notifications:
    email: false

cache:
    directories:
        - $TRAVIS_BUILD_DIR/.hypothesis

install:
    - pip install -r requirements.txt
    - python setup.py develop
    - pip install --upgrade pytest
    - pip install coveralls
    - pip install hypothesis
    - pip install pytest-cov
    - pip install sphinx sphinx_rtd_theme
script:
    - pytest --cov=edo tests
    - pip uninstall -y edo
    - pip install edo
after_success: coveralls
