name: edo-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib>=3.2
  - pip
  - pytest>=5.4
  - pytest-cov>=2.10
  - python>=3.6
  - scipy>=1.5
  - pip:
    - -r requirements.txt
    - -e .
    - black
    - flake8
    - hypothesis==5.20.3
    - isort
