name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt
        python -m pip install -q --no-cache-dir -e .
        python -m pip install -q --no-cache-dir pytest pytest-cov hypothesis
        python -m pip install -q --no-cache-dir black flake8 isort
      python -m pip list
    - name: Run tests
      run: python -m pytest --cov=edo --cov-fail-under=100 tests
    - name: Run linters
      if: matrix.python-version == 3.8 && matrix.os == 'ubuntu-latest'
      run: |
        python -m black --check --diff -l 80 .
        python -m isort -w 80 -m 3 --trailing-comma --check-only .
        python -m flake8 --max-line-length=80 --exclude=docs .
    - name: Check pip install
      run: |
        python -m pip uninstall -y edo
        python -m pip install edo
