name: Documentation

on:
  pull_request:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python setup.py install
        python -m pip install -r docs/requirements.txt
        brew install pandoc
    - name: Check documentation compiles
      run: |
        sphinx-build -b html docs docs/_build/html
        rm -rf docs/_build
    - name: Run doctests
      run: |
        python -m pytest --nbval --current-env docs
        python -m pytest --doctest-glob="*.rst" docs
    - name: Run linters
      run: |
        python -m blackbook .
